#simple
GET http://test:test@localhost:8080/ping

###
# with params
GET http://test:test@localhost:8080/ping/giampaolo

###

GET https://demo:demo@samplegingo-xcigta.apps.lab01.k8s.etat-de-vaud.ch/ping



